name: build

on:
  push:
    branches: [ master ]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Cache Sonar scanner
        id: cache-sonar-scanner
        uses: actions/cache@v4
        with:
          path: .\.sonar\scanner
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner

      - name: Install SonarScanner for .NET
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        shell: powershell
        run: dotnet tool update dotnet-sonarscanner --tool-path .\.sonar\scanner

      - name: Sonar Begin
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: powershell
        run: |
          $sonarCoverageExclusions = "**/Program.cs,**/Startup.cs,**/GlobalUsings.cs,**/Usings.cs,**/*AssemblyInfo*.cs,**/*.g.cs,**/*.generated.cs,**/*.designer.cs,**/Migrations/**,**/Dependencies/**,**/*DependencyInjection*.cs,**/*.http"
          .\.sonar\scanner\dotnet-sonarscanner begin `
            /k:"tavolordk_SIAU.Platform" `
            /o:"tavolordk" `
            /d:sonar.host.url="https://sonarcloud.io" `
            "/d:sonar.cs.opencover.reportsPaths=**/coverage.opencover.xml" `
            "/d:sonar.coverage.exclusions=$sonarCoverageExclusions"

      - name: Restore
        run: dotnet restore SIAU.Platform.sln

      - name: Build
        run: dotnet build SIAU.Platform.sln -c Release --no-restore -p:TreatWarningsAsErrors=false

      # Tests + cobertura usando archivo de respuesta (evita errores MSB1006/MSB1008)
      - name: Test with coverage (and thresholds)
        shell: powershell
        run: |
          $rsp = @"
/p:CollectCoverage=true
/p:CoverletOutput=TestResults/coverage/
/p:CoverletOutputFormat=opencover
/p:ExcludeByFile=**/Program.cs;**/Startup.cs;**/GlobalUsings.cs;**/Usings.cs;**/*AssemblyInfo*.cs;**/*.g.cs;**/*.generated.cs;**/*.designer.cs;**/Migrations/**;**/Dependencies/**;**/*DependencyInjection*.cs;**/*.http
/p:Exclude=[xunit.*]*
/p:ThresholdForLines=80
/p:ThresholdForBranches=70
/p:ThresholdForMethods=80
/p:ThresholdStat=total
"@
          Set-Content -Path msbuild.rsp -Value $rsp -Encoding ascii
          dotnet test SIAU.Platform.sln --no-build -c Release @msbuild.rsp

      - name: Sonar End
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: .\.sonar\scanner\dotnet-sonarscanner end
