- name: Sonar Begin
  env:
    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  shell: powershell
  run: |
    .\.sonar\scanner\dotnet-sonarscanner begin `
      /k:"tavolordk_SIAU.Platform" `
      /o:"tavolordk" `
      /d:sonar.host.url="https://sonarcloud.io" `
      /d:sonar.cs.cobertura.reportsPaths="**/coverage.cobertura.xml" `
      /d:sonar.coverage.exclusions="**/*.g.cs,**/*.generated.cs,**/*.designer.cs"

- name: Test with coverage
  run: >
    dotnet test SIAU.Platform.sln --no-build -c Release
    --collect:"XPlat Code Coverage"
    --logger "trx;LogFileName=test_results.trx"
    --results-directory TestResults

- name: Install ReportGenerator
  run: dotnet tool install --global dotnet-reportgenerator-globaltool

- name: Generate HTML coverage report
  shell: powershell
  run: |
    reportgenerator -reports:**/coverage.cobertura.xml `
                    -targetdir:CoverageReport `
                    -reporttypes:HtmlInline;Cobertura;TextSummary;JsonSummary

- name: Upload coverage HTML as artifact
  uses: actions/upload-artifact@v4
  with:
    name: coverage-html
    path: CoverageReport

- name: Sonar End
  env:
    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  run: .\.sonar\scanner\dotnet-sonarscanner end
